### PR TITLE
Fix 0.7.0 error

### PR DESCRIPTION
**Pull request by junderw**
Is there a way to get the pragma setting?

### CODE REVIEW

**Comment by junderw** [comment]
This is currently a "beat with blunt object" fix for #23

**Comment by fvictorio** [comment]
Hey @junderw, thanks for this!

I think this fix should be enough. So far this parser doesn't do different things for different versions: it's built to accept any valid solidity code for any version. This means that sometimes it can parse solidity code that won't compile, but that's fine for most use cases.

Can you remove the comment and add some tests for this?

**Comment by junderw** [comment]
I removed the comment and added a test to confirm the no-keyword case has visibility of public.

**Comment by fvictorio** [comment]
Thanks @junderw!

**Comment by fvictorio** [comment]
Just published `@solidity-parser/parser@0.7.0` with this change.

**Pull request merged**
